invites/models.py
# coding: utf-8
import uuid

from google.appengine.ext import ndb

__ALL__ = ('Invite', 'Subscribe')


class Invite(ndb.Model):
    """ Модель приглашения.
    """
    uuid = ndb.StringProperty()
    text = ndb.TextProperty(required=True)
    limit = ndb.IntegerProperty(default=1)
    created = ndb.DateTimeProperty(auto_now_add=True)

    # Счетчики
    emails_count = ndb.IntegerProperty(default=0)
    views = ndb.IntegerProperty(default=0)

    def _pre_put_hook(self):
        if not self.uuid:
            self.uuid = unicode(uuid.uuid1())

    DEFAULT_ORDER_BY = '-created'
    ORDER_BY_FIELDS = ('created', 'emails_count', 'views',
                       DEFAULT_ORDER_BY, '-emails_count', '-views')

    @classmethod
    def all_ordered(cls, field):
        """ Выдает отсортированную выборку.
        """
        if field not in cls.ORDER_BY_FIELDS:
            field = cls.DEFAULT_ORDER_BY

        prop = getattr(cls, field[field.startswith('-'):])

        if field.startswith('-'):
            prop = prop.__neg__()

        return cls.query().order(prop)

    @classmethod
    def get_by_uuid(cls, uuid):
        """ Получение по UUID.
        """
        return cls.query(cls.uuid == uuid).get()

    @staticmethod
    def track_and_get(uuid):
        """ Получаем приглашение по его uuid и трекаем это, как просмотр.
        """
        inv = Invite.get_by_uuid(uuid)

        @ndb.transactional
        def incr(key):
            obj = key.get()
            obj.views += 1
            obj.put()

        if inv:
            incr(inv.key)

        return inv

    def is_already_exists(self, email):
        """ По-хорошему надо unique_together еще навернуть.
        """
        return Subscribe.query(Subscribe.invite == self.key,
                               Subscribe.email == email).get()

    @property
    def is_full(self):
        return self.emails_count >= self.limit


class Subscribe(ndb.Model):
    """ Подписка.
    """
    email = ndb.StringProperty(required=True)
    email_domain = ndb.StringProperty()
    created = ndb.DateTimeProperty(auto_now_add=True)

    invite = ndb.KeyProperty(kind=Invite)

    def _pre_put_hook(self):
        self.email_domain = self.email.split('@')[-1]

    def _post_put_hook(self, *args, **kwargs):
        @ndb.transactional
        def incr():
            """ Увеличивает счетчик подписчиков.
            """
            obj = self.invite.get()
            obj.emails_count += 1
            obj.put()

        incr()

invites/forms.py
# coding: utf-8
from flask_wtf import Form
from wtforms.fields import SubmitField, StringField, IntegerField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, ValidationError


__ALL__ = ('InviteForm', 'SubscribeForm')


class InviteForm(Form):
    """ Форма создания нового приглашения.
    """
    text = StringField(u'Приглашения для')
    limit = IntegerField(u'Лимит подписок')
    add = SubmitField(u'Добавить')


class SubscribeForm(Form):
    """ Форма для подписки на приглашение.
    """
    def __init__(self, invite, *args, **kwargs):
        self.invite = invite
        super(SubscribeForm, self).__init__(*args, **kwargs)

    email = EmailField(u'Эл. почта', [Email()])
    subscribe = SubmitField(u'Подписаться!')

    def validate_email(self, field):
        email = field.data

        if self.invite.is_already_exists(email):
            raise ValidationError(u'Вы уже подписались')

invites/__init__.py
# coding: utf-8
""" Модуль работы с приглашениями.
"""
from .views import *

invites/views.py
# coding: utf-8
from collections import Counter

from flask import (Blueprint, redirect, url_for, make_response, request, flash,
                   Response)

from main.utils import render_to, staff_only

from .forms import SubscribeForm, InviteForm
from .models import Invite, Subscribe


invites_app = Blueprint('invites', __name__, template_folder='templates')


@invites_app.route('/invite/<inv:invite>', methods=['GET', 'POST'])
@render_to('invites/invite.jinja')
def invite_page(invite):
    """ Страница подписки
    """
    if invite.is_full:
        flash(u'Вы уже подписались')
        return redirect(url_for('main.index'))

    form = SubscribeForm(invite=invite)
    subscribed = request.cookies.get(invite.uuid)

    if subscribed:
        return locals()

    if form.validate_on_submit():
        sub = Subscribe(email=form.email.data, invite=invite.key)
        sub.put()
        subscribed = True
        COOKIES = ((invite.uuid, invite.uuid),)

    return locals()


@invites_app.route('/admin/invites', methods=['GET', 'POST'])
@render_to('invites/admin.jinja')
@staff_only
def admin_page():
    """ Админка.
    """
    form = InviteForm()

    if form.validate_on_submit():
        inv = Invite(text=form.text.data, limit=form.limit.data)
        inv.put()
        flash(u'Добавлено приглашение для: {}'.format(inv.text))
        return redirect(url_for('invites.admin_page'))

    order = request.args.get('o')
    invites = Invite.all_ordered(order)

    subs = Subscribe.query(projection=[Subscribe.email_domain]).fetch()
    subs_stats = Counter((x.email_domain for x in subs))
    return locals()


@invites_app.route('/admin/subs/grab', methods=['GET'])
@staff_only
def admin_subs_grab():
    """ Скачка файла со списком адресов.
    """
    emails = (u'{}\n'.format(s.email) for s in
              Subscribe.query(projection=[Subscribe.email],
                              distinct=True).fetch())

    return Response(emails, mimetype='text/plain')

invites/templates/invites/admin.jinja
{% extends 'admin.jinja' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% import "bootstrap/utils.html" as utils %}

{% macro render_order_link(name, title) %}
    {% if '-'+name == request.args.o %}
        {% set param=name %}
    {% else %}
        {% set param='-'+name %}
    {% endif %}

    <a href="?o={{ param }}">{{ title }}</a>
{% endmacro %}


{% block content %}
    <div class="col-md-12">
        <h4>Добавить приглашение</h4>
        <div class="col-md-2">
            <div class="row">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>

    <div class="col-md-12" style="margin-top:10px;">
        <hr>
        <h4>Приглашения</h4>
        <div class="row">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Key</th>
                        <th>
                            {{ render_order_link('created', 'Дата создания') }}
                        </th>
                        <th>Для кого</th>
                        <th>Лимит</th>
                        <th>
                            {{ render_order_link('emails_count', 'Подписок') }}
                        </th>
                        <th>
                            {{ render_order_link('views', 'Просмотров') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for inv in invites %}
                        <tr>
                            <td>{{ inv.uuid }}</td>
                            <td>{{ inv.created }}</td>
                            <td>{{ inv.text }}</td>
                            <td>{{ inv.limit }}</td>
                            <td>{{ inv.emails_count }}</td>
                            <td>{{ inv.views }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">Нед подписок</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-12" style="margin-top:10px;">
        <hr>
        <h4>Легкая статистика по подписчикам</h4>

        {{ utils.form_button(url_for('invites.admin_subs_grab'), 'Файл', method='get', class='btn btn-primary') }}

        <br>
        <br>

        <div class="row">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Домен почты</th>
                        <th>Подписчиков</th>
                    </tr>
                </thead>
                <tbody>
                    {% for k, v in subs_stats.items() %}
                        <tr>
                            <td>{{ k }}</td>
                            <td>{{ v }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

invites/templates/invites/invite.jinja
{% extends 'base.jinja' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block navbar__extra_text %}Приглашение для &laquo;{{ invite.text }}&raquo;{% endblock %}

{% block content %}
    {% if subscribed  %}
        Спасибо, что подписались на нас!
    {% else %}
        {{ wtf.quick_form(form, form_type='horizontal', horizontal_columns=('lg', 2, 2)) }}
    {% endif %}
{% endblock %}