main/__init__.py
# coding: utf-8
""" Общий модуль.
"""
from .views import *

main/views.py
# coding: utf-8
from flask import Blueprint, render_template

from main.utils import render_to, staff_only


main_app = Blueprint('main', __name__, template_folder='templates')


@main_app.route('/')
@render_to()
def index():
    return locals()


@main_app.route('/admin')
@render_to('admin.jinja')
@staff_only
def admin_page():
    """ Админка.
    """
    return locals()

main/templates/admin.jinja
{% extends 'base.jinja' %}

{% block navbar__extra_text %}
    <a href="{{ url_for('main.admin_page') }}">Админка</a>
{% endblock %}


{% block navbar__items %}
    <li class="{% if url_for('invites.admin_page') in request.path %}active{% endif %}">
        <a href="{{ url_for('invites.admin_page') }}">Инвайты</a>
    </li>
{% endblock %}

main/templates/base.jinja
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block title %}
    Top Secret App
{% endblock %}

{% block navbar %}
{# Не судите строго, просто сильно лень было :) #}
<style type="text/css">
    .navbar-header {
        width: 50%;
    }

    .navbar-header__extra-text {
        height: 50px;
        padding: 15px;
        color: #6F6F6F;
    }
</style>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Top Secret App</a>
      <div class="navbar-header__extra-text">{% block navbar__extra_text %}{% endblock %}</div>
    </div>
    <ul class="nav navbar-nav">
        {% block navbar__items %}{% endblock %}
    </ul>
  </div>
</nav>

{{ utils.flashed_messages(container=True, default_category='info') }}
{% endblock %}

main/templates/index.jinja
{% extends 'base.jinja' %}

{% block content %}
    Только по приглашениям.
{% endblock %}